//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dot_net_mid_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Customers = new HashSet<Customer>();
            this.Employees = new HashSet<Employee>();
            this.Managers = new HashSet<Manager>();
            this.Orders = new HashSet<Order>();
        }

        public int id { get; set; }
        [Required(ErrorMessage ="Please provide name"),MaxLength(10,ErrorMessage ="name should be less than 10 character")]
        public string name { get; set; }
        [Required(ErrorMessage = "Please provide email"),]
        public string email { get; set; }
        [Required(ErrorMessage = "Please provide phone"),]
        public string phone { get; set; }
        [Required(ErrorMessage = "password can not be empty"),MinLength(4,ErrorMessage ="password should be grater than 4 digit")]
        public string password { get; set; }
        
        
        public int usertype { get; set; }
        [Required(ErrorMessage = "Please provide house name"),]
        public string house { get; set; }
        [Required(ErrorMessage = "Please provide address road"),]
        public string road { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string additional_info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager> Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
